import {AbsoluteFill, useCurrentFrame} from "remotion";
import {coral, fontFamily, good, grid, ink, inkSoft, monoFamily, paper} from "../design";
import {Glyph, restGlyph} from "../film/glyphs";
import {StageContext} from "../remotion/lib/stage";
import {KanbanMove} from "../remotion/scenes/kanban-move";
import {Attention, AppWindow, BookingCalendar, Count, DataTable, FormPanel, Inbox, MetricCard, Notification, ProgressTrack, RecordCard, Reveal, StatusBadge, Workflow} from "./materials";

export const GALLERY_PAGE_FRAMES = 90;
export const GALLERY_PAGES = 6;
export const GALLERY_DURATION = GALLERY_PAGE_FRAMES * GALLERY_PAGES;

const shell: React.CSSProperties = {position:"absolute",left:46,right:46,top:186,bottom:100};
const tiny = (text:string) => <span style={{fontFamily:monoFamily,fontSize:19,color:inkSoft}}>{text}</span>;

const Header = ({page,title,ids}: {page:number;title:string;ids:string[]}) => <><div style={{position:"absolute",left:48,right:48,top:42,display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontFamily:monoFamily,fontSize:18,letterSpacing:2.4,color:coral}}>FOUNDING VISUAL TOOLSET · {String(page+1).padStart(2,"0")}</div><div style={{fontFamily,fontSize:48,fontWeight:800,color:ink,letterSpacing:-1.5,marginTop:8}}>{title}</div></div><div style={{padding:"10px 16px",border:`2px solid ${ink}`,borderRadius:999,fontFamily:monoFamily,fontSize:17,fontWeight:600,color:ink}}>1080 × 1920</div></div><div style={{position:"absolute",left:48,right:48,bottom:37,display:"flex",gap:18,alignItems:"center"}}>{ids.map(tiny)}<span style={{marginLeft:"auto",fontFamily:monoFamily,fontSize:17,color:inkSoft}}>STUDIO OWNED · FRAME DRIVEN · PHONE SAFE</span></div></>;

const CrmPage = ({start}:{start:number}) => <><Header page={0} title="One customer. One changing state." ids={["ui.app-window","ui.crm-record","ui.inbox"]}/><div style={shell}><AppWindow title="Harbor Bakery · CRM" tabs={["Record","Activity","Messages"]}><Reveal startFrame={start+4}><RecordCard id="LEAD-1042" name="Mara Chen" company="Harbor Bakery" status="QUALIFIED" tone="good" fields={[{label:"Owner",value:"Ari"},{label:"Source",value:"Referral"},{label:"Value",value:"$4,800"},{label:"Next",value:"Book call"}]}/></Reveal><div style={{height:22}}/><Inbox selectedId="m2" messages={[{id:"m1",sender:"Mara",subject:"Could Tuesday work?",meta:"9:42",unread:true},{id:"m2",sender:"Agent",subject:"Three times are ready",meta:"9:43",unread:true,tone:"good"},{id:"m3",sender:"CRM",subject:"Lead moved to Qualified",meta:"9:43",tone:"accent"}]}/></AppWindow></div></>;

const SpreadsheetPage = ({start}:{start:number}) => <><Header page={1} title="Test the workflow with fake leads." ids={["ui.data-table","primitive.status-badge","motion.attention"]}/><div style={shell}><AppWindow title="Lead test · sandbox" eyebrow="SPREADSHEET" tabs={["Leads","Runs","Errors"]}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div style={{fontFamily,fontSize:28,fontWeight:800,color:ink}}>4 rows · test data only</div><StatusBadge label="SAFE MODE" tone="accent"/></div><Attention startFrame={start+22}><DataTable columns={["ID","COMPANY","STATE","RESULT"]} selectedId="L-003" rows={[{id:"L-001",cells:["L-001","Juniper","New","Sent"],tone:"good"},{id:"L-002",cells:["L-002","Northstar","New","Sent"],tone:"good"},{id:"L-003",cells:["L-003","Harbor","Reply","Booked"],tone:"accent"},{id:"L-004",cells:["L-004","Morrow","Hold","Skipped"],tone:"neutral"}]}/></Attention><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginTop:20}}><Notification title="Run complete" body="4 rows tested · no live contacts" tone="good"/><ProgressTrack label="Coverage" value={100}/></div></AppWindow></div></>;

const DashboardPage = ({start}:{start:number}) => <><Header page={2} title="Metrics explain a workflow." ids={["ui.metric-card","ui.workflow","motion.count"]}/><div style={shell}><AppWindow title="Outbound agent · today" eyebrow="OPERATIONS"><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}><MetricCard label="Leads" value={<Count to={48} startFrame={start+5}/>} delta="+12 today"/><MetricCard label="Replies" value={<Count to={19} startFrame={start+9}/>} delta="39.6%" tone="good"/><MetricCard label="Booked" value={<Count to={7} startFrame={start+13}/>} delta="7 confirmed" tone="accent"/></div><div style={{marginTop:42,padding:"32px 20px",border:`2px solid ${grid}`,borderRadius:18,background:"#FFFFFF"}}><Workflow steps={["Import","Enrich","Write","Review","Send"]} active={3}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18,marginTop:28}}><ProgressTrack label="Daily goal" value={72}/><ProgressTrack label="Reviewed" value={84}/></div><div style={{marginTop:32,padding:22,borderLeft:`7px solid ${coral}`,background:paper,borderRadius:12,fontFamily,fontSize:27,fontWeight:700,color:ink}}>The dashboard supports the causal story; it does not become the story.</div></AppWindow></div></>;

const BookingPage = ({start}:{start:number}) => <><Header page={3} title="A form becomes a confirmed booking." ids={["ui.form","ui.booking","primitive.notification"]}/><div style={{...shell,bottom:"auto",display:"grid",gridTemplateColumns:"0.9fr 1.1fr",gap:20,alignItems:"start"}}><AppWindow title="Qualification" eyebrow="FORM"><FormPanel filled={4} status="READY" fields={[{label:"Company",value:"Harbor Bakery"},{label:"Team",value:"12 people"},{label:"Goal",value:"Book demos"},{label:"Owner",value:"Mara"}]}/></AppWindow><AppWindow title="Pick a time" eyebrow="BOOKING"><Reveal startFrame={start+8}><BookingCalendar selected="16" status="CONFIRMED" days={[{day:"MON",date:"14",slots:2},{day:"TUE",date:"15",slots:0},{day:"WED",date:"16",slots:3},{day:"THU",date:"17",slots:1},{day:"FRI",date:"18",slots:0}]}/></Reveal><div style={{height:24}}/><Notification title="Meeting booked" body="Wed 16 · 2:30 PM · Mara Chen" tone="good"/></AppWindow></div><div style={{position:"absolute",left:46,right:46,top:1080,padding:"32px 34px",border:`3px solid ${ink}`,borderRadius:22,background:"#FBF9F4",boxShadow:"5px 6px 0 rgba(28,33,43,.14)"}}><div style={{fontFamily:monoFamily,fontSize:18,color:coral,letterSpacing:1.7,marginBottom:24}}>ONE STATEFUL FLOW</div><Workflow steps={["Form","Qualified","Slot","Confirmed"]} active={3}/><div style={{marginTop:28,fontFamily,fontSize:27,fontWeight:700,color:ink}}>The same business object progresses; the interface materials show its evidence.</div></div></>;

const KanbanPage = () => <><Header page={4} title="Video-native material, under house direction." ids={["remotion-ui.kanban-move","action.motion-verbs"]}/><div style={{...shell,top:300,bottom:"auto",height:850,border:`3px solid ${ink}`,borderRadius:24,overflow:"hidden",background:"#FBF9F4",boxShadow:"5px 6px 0 rgba(28,33,43,.14)"}}><div style={{position:"absolute",left:0,right:0,top:-471,height:1792}}><StageContext.Provider value={{width:988,height:1792}}><KanbanMove columns={["NEW","WORKING","DONE"]} backgroundColor="#FBF9F4" accentColor={coral} theme="light" dealStaggerSeconds={0.08} moveSeconds={0.6} cards={[{title:"Lead 1042",meta:"qualified",column:0,tint:coral,moveTo:1,moveAtSeconds:1.2},{title:"Lead 1043",meta:"new",column:0,tint:ink},{title:"Reply 881",meta:"reviewed",column:1,tint:coral,moveTo:2,moveAtSeconds:1.8},{title:"Booking 77",meta:"confirmed",column:2,tint:good}]}/></StageContext.Provider></div></div><div style={{position:"absolute",left:70,right:70,top:1215}}><div style={{fontFamily:monoFamily,fontSize:18,color:coral,letterSpacing:1.7,marginBottom:18}}>ACTION SEMANTICS STAY TYPED</div><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:10}}>{["TRAVERSE","RETURN","TRANSFORM","BLOCK","ACCUMULATE"].map((verb,index)=><div key={verb} style={{padding:"15px 7px",borderRadius:10,textAlign:"center",fontFamily:monoFamily,fontSize:15,fontWeight:600,color:index===2?"#FFF":ink,background:index===2?coral:paper,border:`2px solid ${index===2?coral:grid}`}}>{verb}</div>)}</div><div style={{marginTop:25,padding:"20px 24px",borderLeft:`7px solid ${coral}`,background:"#FBF9F4",fontFamily,fontSize:27,fontWeight:700,color:ink}}>The board supplies material. FilmDirection still decides what changes and why.</div></div></>;

const LanguagePage = ({start}:{start:number}) => <><Header page={5} title="A bounded vocabulary, ready to combine." ids={["house.persistent-glyph","bespoke.react-svg","motion.reveal"]}/><div style={{...shell,display:"grid",gridTemplateRows:"430px 1fr",gap:28}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:16}}>{(["message","agent","document","sheet"] as const).map((kind,index)=><Reveal key={kind} startFrame={start+index*4}><div style={{height:390,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",border:`3px solid ${ink}`,borderRadius:20,background:"#FBF9F4",boxShadow:"4px 5px 0 rgba(28,33,43,.12)"}}><svg width="190" height="190" viewBox="-100 -100 200 200"><Glyph kind={kind} g={{...restGlyph,unread:kind==="message"?1:0,bar:kind==="agent"?.7:0,open:kind==="message"?.35:0}}/></svg><div style={{fontFamily:fontFamily,fontSize:25,fontWeight:800,color:ink,textTransform:"capitalize"}}>{kind}</div><div style={{fontFamily:monoFamily,fontSize:15,color:inkSoft,marginTop:6}}>STABLE ID</div></div></Reveal>)}</div><div style={{padding:30,border:`3px solid ${ink}`,borderRadius:22,background:"#FBF9F4"}}><div style={{fontFamily:monoFamily,fontSize:18,letterSpacing:1.6,color:coral}}>DISCOVER BY MEANING</div><div style={{fontFamily,fontSize:35,fontWeight:800,color:ink,marginTop:12}}>“I need a customer record whose status changes.”</div><div style={{display:"flex",flexWrap:"wrap",gap:12,marginTop:24}}>{["record","status","timeline","notification","persistent identity","choreographable"].map((tag,index)=><span key={tag} style={{padding:"12px 17px",borderRadius:999,border:`2px solid ${index<4?ink:grid}`,background:index<4?"#FFF":paper,fontFamily:monoFamily,fontSize:19,fontWeight:600,color:index===1?coral:ink}}>{tag}</span>)}</div><div style={{height:2,background:grid,margin:"30px 0"}}/><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:15}}>{[["29","APPROVED IDS"],["0","NEW PACKAGES"],["1","FROZEN SET"]].map(([value,label])=><div key={label} style={{padding:20,borderRadius:15,background:paper}}><div style={{fontFamily,fontSize:44,fontWeight:800,color:value==="0"?good:ink}}>{value}</div><div style={{fontFamily:monoFamily,fontSize:16,color:inkSoft}}>{label}</div></div>)}</div></div></div></>;

export const FoundingToolsetGallery = () => {
  const frame = useCurrentFrame();
  const page = Math.min(GALLERY_PAGES-1, Math.floor(frame/GALLERY_PAGE_FRAMES));
  const start = page*GALLERY_PAGE_FRAMES;
  return <AbsoluteFill style={{backgroundColor:paper,backgroundImage:`linear-gradient(${grid} 1px,transparent 1px),linear-gradient(90deg,${grid} 1px,transparent 1px)`,backgroundSize:"40px 40px",overflow:"hidden"}}>{page===0?<CrmPage start={start}/>:page===1?<SpreadsheetPage start={start}/>:page===2?<DashboardPage start={start}/>:page===3?<BookingPage start={start}/>:page===4?<KanbanPage/>:<LanguagePage start={start}/>}</AbsoluteFill>;
};
