import type {CSSProperties, ReactNode} from "react";
import {interpolate, useCurrentFrame} from "remotion";
import {materialTokens as t} from "./tokens";

const clamp = {extrapolateLeft: "clamp", extrapolateRight: "clamp"} as const;
const toneColor = (tone: StatusTone = "neutral") => tone === "good" ? t.color.good : tone === "bad" ? t.color.bad : tone === "accent" ? t.color.accent : t.color.inkSoft;
export type StatusTone = "neutral" | "accent" | "good" | "bad";

export const Reveal = ({children, startFrame = 0, duration = t.motion.revealFrames, style}: {children: ReactNode; startFrame?: number; duration?: number; style?: CSSProperties}) => {
  const frame = useCurrentFrame();
  const p = interpolate(frame, [startFrame, startFrame + duration], [0, 1], clamp);
  return <div style={{opacity: p, transform: `translateY(${(1 - p) * 16}px)`, ...style}}>{children}</div>;
};

export const Count = ({from = 0, to, startFrame = 0, duration = 24, prefix = "", suffix = ""}: {from?: number; to: number; startFrame?: number; duration?: number; prefix?: string; suffix?: string}) => {
  const frame = useCurrentFrame();
  const value = interpolate(frame, [startFrame, startFrame + duration], [from, to], clamp);
  return <>{prefix}{Math.round(value).toLocaleString("en-US")}{suffix}</>;
};

export const Attention = ({children, active = true, startFrame = 0}: {children: ReactNode; active?: boolean; startFrame?: number}) => {
  const frame = useCurrentFrame();
  const age = Math.max(0, frame - startFrame);
  const pulse = active && age < t.motion.attentionFrames ? Math.sin(age / t.motion.attentionFrames * Math.PI) : 0;
  return <div style={{transform: `scale(${1 + pulse * 0.035})`, filter: `drop-shadow(0 0 ${pulse * 14}px rgba(226,91,58,.35))`}}>{children}</div>;
};

export const StatusBadge = ({label, tone = "neutral"}: {label: string; tone?: StatusTone}) => {
  const color = toneColor(tone);
  return <span style={{display:"inline-flex",alignItems:"center",gap:10,border:`2px solid ${color}`,borderRadius:t.radius.chip,padding:"8px 15px",fontFamily:t.type.mono,fontSize:22,fontWeight:600,color,background:t.color.white,whiteSpace:"nowrap"}}><span style={{width:9,height:9,borderRadius:9,background:color}}/>{label}</span>;
};

export const Tabs = ({labels, active = 0}: {labels: string[]; active?: number}) => <div style={{display:"flex",gap:8,padding:7,border:`2px solid ${t.color.grid}`,background:t.color.paper,borderRadius:14}}>{labels.slice(0,4).map((label,index)=><div key={label} style={{flex:1,padding:"11px 9px",borderRadius:9,textAlign:"center",fontFamily:t.type.body,fontSize:23,fontWeight:700,color:index===active?t.color.white:t.color.inkSoft,background:index===active?t.color.ink:"transparent"}}>{label}</div>)}</div>;

export const AppWindow = ({title, eyebrow = "WORKSPACE", tabs, activeTab = 0, children, style}: {title: string; eyebrow?: string; tabs?: string[]; activeTab?: number; children: ReactNode; style?: CSSProperties}) => <div style={{border:`3px solid ${t.color.ink}`,borderRadius:t.radius.window,background:t.color.surface,boxShadow:t.shadow,overflow:"hidden",...style}}><div style={{height:84,display:"flex",alignItems:"center",padding:"0 24px",gap:18,borderBottom:`3px solid ${t.color.ink}`,background:t.color.paper}}><div style={{display:"flex",gap:9}}>{[t.color.bad,"#E8B43A",t.color.good].map(color=><span key={color} style={{width:15,height:15,borderRadius:15,background:color}}/>)}</div><div style={{minWidth:0}}><div style={{fontFamily:t.type.mono,fontSize:15,letterSpacing:1.8,color:t.color.inkSoft}}>{eyebrow}</div><div style={{fontFamily:t.type.body,fontSize:27,fontWeight:800,color:t.color.ink,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{title}</div></div></div><div style={{padding:22}}>{tabs?<div style={{marginBottom:20}}><Tabs labels={tabs} active={activeTab}/></div>:null}{children}</div></div>;

export type RecordField = {label: string; value: string};
export const RecordCard = ({id,name,company,status,fields,tone="accent"}: {id:string;name:string;company:string;status:string;fields:RecordField[];tone?:StatusTone}) => <div style={{padding:24,border:`2px solid ${t.color.ink}`,borderRadius:t.radius.card,background:t.color.white}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:16}}><div><div style={{fontFamily:t.type.mono,fontSize:18,color:t.color.inkSoft}}>{id}</div><div style={{fontFamily:t.type.body,fontSize:38,fontWeight:800,color:t.color.ink,lineHeight:1.08}}>{name}</div><div style={{fontFamily:t.type.body,fontSize:25,color:t.color.inkSoft,marginTop:4}}>{company}</div></div><StatusBadge label={status} tone={tone}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginTop:23}}>{fields.slice(0,4).map(field=><div key={field.label} style={{padding:"14px 16px",background:t.color.paper,borderRadius:12}}><div style={{fontFamily:t.type.mono,fontSize:16,color:t.color.inkSoft,textTransform:"uppercase"}}>{field.label}</div><div style={{fontFamily:t.type.body,fontSize:25,fontWeight:700,color:t.color.ink,marginTop:4}}>{field.value}</div></div>)}</div></div>;

export type TableRow = {id: string; cells: string[]; tone?: StatusTone};
export const DataTable = ({columns,rows,selectedId,revealed=rows.length}: {columns:string[];rows:TableRow[];selectedId?:string;revealed?:number}) => <div style={{border:`2px solid ${t.color.ink}`,borderRadius:16,overflow:"hidden",background:t.color.white}}><div style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(4,columns.length)},1fr)`,background:t.color.ink,color:t.color.white}}>{columns.slice(0,4).map(column=><div key={column} style={{padding:"14px 13px",fontFamily:t.type.mono,fontSize:17,fontWeight:600,borderRight:"1px solid rgba(255,255,255,.18)"}}>{column}</div>)}</div>{rows.slice(0,revealed).slice(0,5).map((row,index)=><div key={row.id} style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(4,columns.length)},1fr)`,background:row.id===selectedId?"rgba(226,91,58,.12)":index%2?t.color.paper:t.color.white,borderTop:`2px solid ${t.color.grid}`,boxShadow:row.id===selectedId?`inset 6px 0 ${toneColor(row.tone??"accent")}`:undefined}}>{row.cells.slice(0,4).map((cell,i)=><div key={`${row.id}-${i}`} style={{padding:"15px 13px",fontFamily:i===0?t.type.mono:t.type.body,fontSize:21,fontWeight:i===0?600:700,color:row.tone&&i===row.cells.length-1?toneColor(row.tone):t.color.ink,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{cell}</div>)}</div>)}</div>;

export type MessageRow = {id:string;sender:string;subject:string;meta:string;unread?:boolean;tone?:StatusTone};
export const Inbox = ({messages,selectedId}: {messages:MessageRow[];selectedId?:string}) => <div style={{display:"grid",gap:10}}>{messages.slice(0,4).map(message=><div key={message.id} style={{display:"grid",gridTemplateColumns:"20px 1fr auto",gap:14,alignItems:"center",padding:"16px 18px",border:`2px solid ${message.id===selectedId?t.color.accent:t.color.grid}`,borderRadius:14,background:message.id===selectedId?"rgba(226,91,58,.08)":t.color.white}}><span style={{width:11,height:11,borderRadius:11,background:message.unread?toneColor(message.tone??"accent"):t.color.grid}}/><div style={{minWidth:0}}><div style={{display:"flex",gap:10,alignItems:"baseline"}}><b style={{fontFamily:t.type.body,fontSize:24,color:t.color.ink}}>{message.sender}</b><span style={{fontFamily:t.type.mono,fontSize:16,color:t.color.inkSoft}}>{message.meta}</span></div><div style={{fontFamily:t.type.body,fontSize:22,color:t.color.inkSoft,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{message.subject}</div></div><span style={{fontFamily:t.type.body,fontSize:28,color:t.color.inkSoft}}>›</span></div>)}</div>;

export const MetricCard = ({label,value,delta,tone="accent",bars=[.25,.45,.4,.72,.82]}: {label:string;value:ReactNode;delta:string;tone?:StatusTone;bars?:number[]}) => {const color=toneColor(tone);return <div style={{padding:21,border:`2px solid ${t.color.ink}`,borderRadius:t.radius.card,background:t.color.white}}><div style={{fontFamily:t.type.mono,fontSize:17,color:t.color.inkSoft,textTransform:"uppercase"}}>{label}</div><div style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between",gap:14,marginTop:12}}><div><div style={{fontFamily:t.type.body,fontSize:49,fontWeight:800,color:t.color.ink,lineHeight:1}}>{value}</div><div style={{fontFamily:t.type.body,fontSize:21,fontWeight:700,color,marginTop:8}}>{delta}</div></div><div style={{display:"flex",alignItems:"flex-end",gap:6,height:70}}>{bars.map((bar,index)=><span key={index} style={{width:15,height:bar*70,background:index===bars.length-1?color:t.color.grid,borderRadius:"5px 5px 1px 1px"}}/>)}</div></div></div>};

export const FormPanel = ({fields,filled,status}: {fields:{label:string;value:string}[];filled:number;status?:string}) => <div style={{display:"grid",gap:13}}>{fields.slice(0,4).map((field,index)=><div key={field.label} style={{padding:"13px 16px",border:`2px solid ${index<filled?t.color.ink:t.color.grid}`,borderRadius:13,background:t.color.white}}><div style={{fontFamily:t.type.mono,fontSize:16,color:t.color.inkSoft}}>{field.label.toUpperCase()}</div><div style={{height:31,fontFamily:t.type.body,fontSize:24,fontWeight:700,color:index<filled?t.color.ink:t.color.grid,marginTop:3}}>{index<filled?field.value:"—"}</div></div>)}{status?<StatusBadge label={status} tone={filled>=fields.length?"good":"accent"}/>:null}</div>;

export const BookingCalendar = ({days,selected,status}: {days:{day:string;date:string;slots:number}[];selected?:string;status:string}) => <div><div style={{display:"grid",gridTemplateColumns:`repeat(${Math.min(days.length,5)},1fr)`,gap:9}}>{days.slice(0,5).map(day=>{const on=day.date===selected;return <div key={day.date} style={{padding:"14px 7px",textAlign:"center",border:`2px solid ${on?t.color.accent:t.color.grid}`,borderRadius:13,background:on?"rgba(226,91,58,.10)":t.color.white}}><div style={{fontFamily:t.type.mono,fontSize:15,color:t.color.inkSoft}}>{day.day}</div><div style={{fontFamily:t.type.body,fontSize:30,fontWeight:800,color:t.color.ink,margin:"3px 0"}}>{day.date}</div><div style={{fontFamily:t.type.body,fontSize:18,fontWeight:700,color:day.slots?t.color.good:t.color.bad}}>{day.slots?`${day.slots} slots`:"Full"}</div></div>})}</div><div style={{marginTop:17,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:t.type.body,fontSize:24,fontWeight:700,color:t.color.ink}}>{selected?`${selected} · 2:30 PM`:"Choose a slot"}</span><StatusBadge label={status} tone={selected?"good":"neutral"}/></div></div>;

export const Workflow = ({steps,active}: {steps:string[];active:number}) => <div style={{display:"flex",alignItems:"flex-start"}}>{steps.slice(0,5).map((step,index)=><div key={step} style={{display:"flex",alignItems:"flex-start",flex:index===steps.length-1?"0 1 140px":1}}><div style={{width:120,textAlign:"center"}}><div style={{width:52,height:52,borderRadius:52,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"center",border:`3px solid ${index<=active?t.color.ink:t.color.grid}`,background:index<active?t.color.good:index===active?t.color.accent:t.color.white,color:index<=active?t.color.white:t.color.inkSoft,fontFamily:t.type.mono,fontSize:21,fontWeight:700}}>{index<active?"✓":index+1}</div><div style={{fontFamily:t.type.body,fontSize:20,fontWeight:index===active?800:600,color:index<=active?t.color.ink:t.color.inkSoft,marginTop:10,lineHeight:1.1}}>{step}</div></div>{index<steps.length-1?<div style={{height:4,flex:1,background:index<active?t.color.good:t.color.grid,marginTop:24,borderRadius:4}}/>:null}</div>)}</div>;

export const ProgressTrack = ({label,value}: {label:string;value:number}) => <div><div style={{display:"flex",justifyContent:"space-between",fontFamily:t.type.body,fontSize:22,fontWeight:700,color:t.color.ink,marginBottom:9}}><span>{label}</span><span>{Math.round(value)}%</span></div><div style={{height:17,borderRadius:17,background:t.color.grid,overflow:"hidden"}}><div style={{width:`${Math.max(0,Math.min(100,value))}%`,height:"100%",background:t.color.accent,borderRadius:17}}/></div></div>;

export const Notification = ({title,body,tone="good"}: {title:string;body:string;tone?:StatusTone}) => {const color=toneColor(tone);return <div style={{display:"grid",gridTemplateColumns:"14px 1fr",gap:15,padding:"17px 19px",border:`2px solid ${t.color.ink}`,borderRadius:15,background:t.color.white,boxShadow:"3px 3px 0 rgba(28,33,43,.12)"}}><span style={{width:12,height:12,borderRadius:12,background:color,marginTop:8}}/><div><div style={{fontFamily:t.type.body,fontSize:25,fontWeight:800,color:t.color.ink}}>{title}</div><div style={{fontFamily:t.type.body,fontSize:21,color:t.color.inkSoft,marginTop:3}}>{body}</div></div></div>};
