import type { MaterialDefinition, MaterialQuery } from "./types";

const p = (path: string) => `src/${path}`;

export const foundingMaterials: readonly MaterialDefinition[] = [
  {id:"house.persistent-glyph",name:"Persistent narrative glyph",source:"house",categories:["narrative-object"],intents:["recurring story object","causal mechanism","persistent identity","state change"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["kind","stable id","continuous glyph state","palette"],animation:"FilmDirection events rendered through sceneAt",limitations:["Six approved object kinds; bespoke art remains available"],provenance:"House glyph and choreography system",localPath:p("film/glyphs.tsx")},
  {id:"house.directed-stage",name:"Directed object stage",source:"house",categories:["container","workflow","narrative-object"],intents:["whole-film continuity","carry","reframe","recap"],visualRole:"foundation",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["FilmDirection","word alignment","chapters"],animation:"Pure choreography with sceneAt as timing authority",limitations:["Director supplies semantic objects, never coordinates"],provenance:"House DirectedStage",localPath:p("film/DirectedStage.tsx")},
  {id:"action.motion-verbs",name:"Action Registry motion verbs",source:"action-registry",categories:["action","workflow"],intents:["traverse","return","transform","block","accumulate"],visualRole:"motion",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["source id","target id","cue","state","outcome"],animation:"Cue-aligned typed MotionShape",limitations:["Actions require a meaningful source/target or in-place transformation"],provenance:"House Action Registry and choreography vocabulary",localPath:p("film/choreography.ts")},

  {id:"remotion-ui.kanban-move",name:"Kanban board",source:"remotion-ui",categories:["kanban","workflow","status"],intents:["queue","pipeline","work moving between states"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["columns","cards","column state"],animation:"Frame-driven deal and move; production state is cue patched",limitations:["Three or four short columns only at phone scale"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/kanban-move/index.tsx"),catalogName:"kanban-move"},
  {id:"remotion-ui.comparison-table",name:"Comparison table",source:"remotion-ui",categories:["comparison","table"],intents:["compare options","feature matrix","pass/fail"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["columns","rows","cells"],animation:"Frame-derived row reveal",limitations:["At most four columns and terse cells"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/comparison-table/index.tsx"),catalogName:"comparison-table"},
  {id:"remotion-ui.form-fill",name:"Form fill sequence",source:"remotion-ui",categories:["form","checklist","status"],intents:["data entry","approval","setup","validation"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["fields","values","validation"],animation:"Frame-driven fill sequence; cue patches freeze truthful state",limitations:["Use five fields or fewer"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/form-fill-sequence/index.tsx"),catalogName:"form-fill-sequence"},
  {id:"remotion-ui.notifications",name:"Notification stack",source:"remotion-ui",categories:["notification","status","message"],intents:["arrival","alert","completion","exception"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["toasts","tone","arrival"],animation:"Frame-derived arrival and dismissal",limitations:["Supporting layer; not a whole chapter stage by itself"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/notification-stack/index.tsx"),catalogName:"notification-stack"},
  {id:"remotion-ui.timeline",name:"Timeline steps",source:"remotion-ui",categories:["timeline","workflow","progress"],intents:["ordered process","milestones","history"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["steps","active step"],animation:"Frame-driven step reveal",limitations:["Five terse steps maximum"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/timeline-steps/index.tsx"),catalogName:"timeline-steps"},
  {id:"remotion-ui.calendar",name:"Calendar month",source:"remotion-ui",categories:["calendar","booking"],intents:["schedule","availability","booking state"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["month","events","selected date"],animation:"Frame-derived event fill",limitations:["Use event marks and one focus; dense labels are not phone safe"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/calendar-month-fill/index.tsx"),catalogName:"calendar-month-fill"},
  {id:"remotion-ui.stat-card",name:"Animated metric",source:"remotion-ui",categories:["metric","dashboard","progress"],intents:["single KPI","count","change","limit"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["value","max","delta","label"],animation:"Deterministic counter and ring",limitations:["One metric; pair with context rather than a decorative dashboard"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/stat-card/index.tsx"),catalogName:"stat-card"},
  {id:"remotion-ui.data-flow",name:"Data flow pipes",source:"remotion-ui",categories:["workflow","action"],intents:["integration","API flow","routing","fan in/out"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["nodes","connections","active paths"],animation:"Deterministic path travel",limitations:["Use Action Registry when persistent story objects must travel"],provenance:"RemotionUI vendored local component",localPath:p("remotion/scenes/data-flow-pipes/index.tsx"),catalogName:"data-flow-pipes"},
  {id:"remotion-ui.progress",name:"Progress bar",source:"remotion-ui",categories:["progress","status"],intents:["completion","quota","bounded progress"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["value","label","tone"],animation:"Deterministic frame-derived fill",limitations:["Requires a meaningful denominator"],provenance:"RemotionUI vendored local component",localPath:p("remotion/primitives/progress-bar.tsx"),catalogName:"progress-bar"},

  {id:"ui.app-window",name:"Software window shell",source:"uiable-adapted",categories:["app-window","container","navigation"],intents:["software interior","browser","SaaS screen","workspace"],visualRole:"foundation",stateful:false,choreographable:false,phoneSafe:true,persistentIdentity:true,inputs:["title","eyebrow","tabs","active tab","children"],animation:"Host-controlled",limitations:["Interior must have one dominant task"],provenance:"Studio adapter after UIAble business UI review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.crm-record",name:"CRM record card",source:"uiable-adapted",categories:["record","card","status"],intents:["customer record","lead state","account owner","next action"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["stable id","name","company","status","fields"],animation:"Prop state with deterministic emphasis",limitations:["Four visible fields maximum"],provenance:"Studio adapter after UIAble card/data display review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.data-table",name:"Data table / spreadsheet",source:"uiable-adapted",categories:["table","spreadsheet","record"],intents:["fake leads","rows","selection","typed data","batch testing"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["columns","rows","selected row","revealed rows"],animation:"Cue-friendly row reveal and stable selection",limitations:["Four columns and five rows per phone frame"],provenance:"Studio adapter after UIAble data-table review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.inbox",name:"Inbox / message list",source:"uiable-adapted",categories:["inbox","message","status"],intents:["email","outreach","reply state","conversation queue"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["messages","selected id","unread state"],animation:"Deterministic row reveal and selection",limitations:["Four messages per frame; message bodies need a detail shot"],provenance:"Studio adapter after UIAble list/data display review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.form",name:"Business form",source:"uiable-adapted",categories:["form","checklist","status"],intents:["setup","qualification","approval","data collection"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["fields","filled count","submit status"],animation:"Frame-independent truth state plus deterministic reveal",limitations:["Four fields; no browser validation dependency"],provenance:"Studio adapter after UIAble form review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.booking",name:"Booking calendar",source:"uiable-adapted",categories:["calendar","booking","status"],intents:["availability","slot selection","confirmation"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["days","slots","selected slot","status"],animation:"Prop-driven selection and confirmation",limitations:["Week slice rather than dense month view"],provenance:"Studio adapter after UIAble calendar review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.metric-card",name:"Dashboard metric card",source:"uiable-adapted",categories:["dashboard","metric","chart"],intents:["KPI","trend","pipeline total","conversion"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["label","value","delta","sparkline"],animation:"Deterministic count and sparkline reveal",limitations:["Maximum three cards; every metric needs narrative relevance"],provenance:"Studio adapter after UIAble chart/card review",localPath:p("founding-toolset/materials.tsx")},
  {id:"ui.workflow",name:"Workflow lane",source:"uiable-adapted",categories:["workflow","status","progress"],intents:["automation","pipeline","handoff","state machine"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["steps","active index","result state"],animation:"Prop-driven active and completed steps",limitations:["Five steps maximum; use Action Registry for physical causality"],provenance:"Studio adapter after UIAble status/step review",localPath:p("founding-toolset/materials.tsx")},

  {id:"motion.reveal",name:"Content reveal",source:"react-bits-adapted",categories:["transition","text-treatment"],intents:["reveal","hierarchy","sequence"],visualRole:"motion",stateful:false,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["children","start frame","duration"],animation:"useCurrentFrame interpolation",limitations:["No autonomous loop; reveal only when meaning changes"],provenance:"Studio deterministic adaptation after React Bits animation review",localPath:p("founding-toolset/materials.tsx")},
  {id:"motion.count",name:"Deterministic counter",source:"react-bits-adapted",categories:["text-treatment","metric"],intents:["count","accumulate","numeric change"],visualRole:"motion",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["from","to","start frame","duration","format"],animation:"Frame-derived interpolation",limitations:["Numbers must be narrated or declared data"],provenance:"Studio deterministic adaptation after React Bits text animation review",localPath:p("founding-toolset/materials.tsx")},
  {id:"motion.attention",name:"Attention pulse",source:"react-bits-adapted",categories:["attention-effect","status"],intents:["focus","state change","exception"],visualRole:"annotation",stateful:false,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["children","active","start frame"],animation:"Single damped frame-driven pulse",limitations:["One focal target; never loop for decoration"],provenance:"Studio deterministic adaptation after React Bits effects review",localPath:p("founding-toolset/materials.tsx")},
  {id:"motion.grid",name:"Studio grid background",source:"react-bits-adapted",categories:["background"],intents:["technical context","software space","alignment"],visualRole:"foundation",stateful:false,choreographable:false,phoneSafe:true,persistentIdentity:false,inputs:["density","opacity"],animation:"Static",limitations:["Low contrast; must not compete with data"],provenance:"Studio tokens over existing local DynamicGrid role",localPath:p("remotion/primitives/dynamic-grid.tsx"),catalogName:"dynamic-grid"},

  {id:"primitive.status-badge",name:"Status badge",source:"shadcn-adapted",categories:["status","card"],intents:["state","tone","approval","exception"],visualRole:"annotation",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["label","tone"],animation:"Host controlled",limitations:["Short state labels only"],provenance:"Studio adapter after shadcn Badge review",localPath:p("founding-toolset/materials.tsx")},
  {id:"primitive.tabs",name:"Tabs",source:"shadcn-adapted",categories:["navigation","container"],intents:["software sections","mode switch","before/after"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["labels","active index"],animation:"Prop-driven active state",limitations:["Four labels; no hover or keyboard runtime required for render"],provenance:"Studio adapter after shadcn Tabs review",localPath:p("founding-toolset/materials.tsx")},
  {id:"primitive.progress",name:"Progress track",source:"shadcn-adapted",categories:["progress","status"],intents:["completion","limit","stage progress"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["value","label"],animation:"Deterministic width interpolation",limitations:["Use only when the denominator is meaningful"],provenance:"Studio adapter after shadcn Progress review",localPath:p("founding-toolset/materials.tsx")},
  {id:"primitive.notification",name:"Compact notification",source:"shadcn-adapted",categories:["notification","message","status"],intents:["confirmation","alert","new event"],visualRole:"support",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:false,inputs:["title","body","tone"],animation:"Host-controlled reveal",limitations:["One compact event; use inbox for history"],provenance:"Studio adapter after shadcn Sonner/Card review",localPath:p("founding-toolset/materials.tsx")},

  {id:"bespoke.react-svg",name:"Bespoke React / SVG",source:"bespoke",categories:["narrative-object","container"],intents:["film-specific metaphor","missing visual","custom explanatory art"],visualRole:"stage",stateful:true,choreographable:true,phoneSafe:true,persistentIdentity:true,inputs:["typed film-specific props","FilmDirection hooks where useful"],animation:"Remotion frame functions and house choreography",limitations:["Must pass the same deterministic, phone and provenance review"],provenance:"Existing studio custom-art escape hatch",localPath:p("film/bespoke.tsx")},
] as const;

const words = (value: string) => value.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
export const materialById = new Map(foundingMaterials.map((material) => [material.id, material]));
export const approvedCatalogNames = new Set(foundingMaterials.flatMap((material) => material.catalogName ? [material.catalogName] : []));

export const discoverMaterials = (query: MaterialQuery) => {
  const needle = new Set(words(query.text ?? ""));
  return foundingMaterials
    .filter((m) => query.categories?.every((category) => m.categories.includes(category)) ?? true)
    .filter((m) => query.stateful == null || m.stateful === query.stateful)
    .filter((m) => query.choreographable == null || m.choreographable === query.choreographable)
    .filter((m) => query.phoneSafe == null || m.phoneSafe === query.phoneSafe)
    .filter((m) => query.persistentIdentity == null || m.persistentIdentity === query.persistentIdentity)
    .map((material) => {
      const field = words([material.name, ...material.categories, ...material.intents].join(" "));
      const score = needle.size ? field.reduce((sum, word) => sum + (needle.has(word) ? 1 : 0), 0) : 1;
      return {material, score};
    })
    .filter(({score}) => score > 0)
    .sort((a, b) => b.score - a.score || a.material.id.localeCompare(b.material.id))
    .slice(0, query.limit ?? 8)
    .map(({material}) => material);
};

/** Compact meaning-first view intended for prompts and future learning records. */
export const materialDiscoveryIndex = foundingMaterials.map(({id, categories, intents, stateful, choreographable, phoneSafe}) => ({id, categories, intents, stateful, choreographable, phoneSafe}));
