import json, pathlib, sys, datetime, hashlib

root=pathlib.Path('out/continuity-v1')
mara=root/'mara-v1-production'
cold=root/'larkspur-verified'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
service=read(root/'service-verification.json')
reports={name:{kind:read(folder/file) for kind,file in [('technical','technical-qc.json'),('conformance','conformance.json'),('audit','continuity-audit.json'),('critic','critic-gaps/critic.json'),('targeted','critic-targeted/critic.json')]} for name,folder in [('Mara',mara),('Larkspur',cold)]}
comparison=read(mara/'comparison-critic/comparison.json')
framecheck=read(cold/'evidence/frame-by-frame-render-check.json')
assert service['ok'] and comparison['complete'] and len(comparison['findings'])==13
assert all(not r['technical']['failed'] and r['conformance']['ok'] and r['critic']['complete'] and r['targeted']['complete'] for r in reports.values())
assert framecheck['ok']
for name,folder in [('Mara',mara),('Larkspur',cold)]:
    manifest=read(folder/'evidence/manifest.json')
    assert hashlib.sha256((folder/'film.mp4').read_bytes()).hexdigest()==manifest['candidateSha256']
    assert hashlib.sha256(pathlib.Path(manifest['baseline']).read_bytes()).hexdigest()==manifest['baselineSha256']==reports[name]['audit']['baselineVideoSha256']
    for kind in ['critic-gaps','critic-targeted']:
        input_file=folder/kind/'critic-input.json'
        if input_file.exists():
            critic_input=read(input_file)
            assert critic_input['videoSha256']==manifest['candidateSha256']
            assert critic_input['propsSha256']==hashlib.sha256((folder/'props.json').read_bytes()).hexdigest()
direction=read(mara/'film-direction.json')
recommendation=sys.argv[1] if len(sys.argv)>1 else 'REVIEW REQUIRED'
grows='\n'.join(f"| {f.get('ruleCode',f['rule'])} | {f['comparison']} | {'Yes' if f['acceptanceMet'] else 'No'} | {'; '.join(f['remainingDefects']).replace('|','/')} |" for f in comparison['findings'])
counts='; '.join(f"{name}: gaps {r['critic']['flagged']}/{r['critic']['frames']}, targeted {r['targeted']['flagged']}/{r['targeted']['frames']} flagged" for name,r in reports.items())
core=['G01','G02','G03','G04','G07','G10','G11','G13']
corestatus=', '.join(f"{f.get('ruleCode',f['rule'])} {f['comparison']}" for f in comparison['findings'] if f.get('ruleCode',f['rule']) in core)
if recommendation.startswith('PASS'):
    assert all(f['comparison']=='improved' for f in comparison['findings'] if f.get('ruleCode',f['rule']) in core), 'A PASS recommendation requires the eight core comparisons to improve'
text=f'''Continuity & Film Direction v1 — acceptance evidence

Recommendation: **{recommendation}**. This is evidence for Source of Truth reconciliation, not approval to start a later phase.

The real path was verified. Authenticated direction and image-input vision requests initially succeeded with the configured Anthropic production model. Its credits were exhausted during a later vision sweep; that partial critique stays failed. The worktree's configured real OpenAI gpt-4.1 provider then passed authenticated text and image requests and supplies the final Mara vision reviews. Provider/model/request IDs are recorded per response; the provider change prevents treating cross-provider flag counts as a calibrated quality metric. Every requested Archivo and IBM Plex Mono production font file returned HTTP 200. Complete Remotion production MP4s use the retained Eric A recordings, unchanged scripts and ElevenLabs word alignment. No quarantined artifact, offline font or substitute direction fixture is acceptance evidence.

All retained baseline videos remain at their original paths. Their SHA-256 values are recorded in the candidate audits and comparison manifests. Failed/truncated API attempts and rejected initial production candidates remain as loop history; their results are not final acceptance.

| Item | Required evidence | Implementation / artifact |
| --- | --- | --- |
| 1 | FilmDirection schema | [src/film/direction.ts](../../src/film/direction.ts): version, through-line, stable objects, sentence-scoped cues, actual/conditional/recap events, typed boundary/composition/presenter/focus/recap shots. |
| 2 | Mara artifact | [film-direction.json](mara-v1-production/film-direction.json): {len(direction['objects'])} objects, {len(direction['events'])} events, {len(direction['shots'])} shots. Generated by the real API, repaired through real critique and recorded per-film review. |
| 3 | Downstream consumption | [server/direct-structure.ts](../../server/direct-structure.ts) supplies typed objects/events/chapter shots to beats and stages and stores the direction in StructuredPlan; timing/Studio/production preserve it; [DirectedStage](../../src/film/DirectedStage.tsx) executes it. |
| 4 | Files changed | Inventory below. The supplied worktree has no .git metadata, so no Git diff is claimed. |
| 5 | Pass ordering | Structure → whole-film direction → chapter beats → stages → recorded alignment → render. Candidate regeneration reuses the retained structure/alignment, without rebuilding completed local work or narration. |
| 6 | Cue-aware component state | [state-cues.ts](../../src/film/state-cues.ts), [StructuredFilm.tsx](../../src/film/StructuredFilm.tsx), [normalizer](../../src/film/normalize.ts). Props change only at aligned phrase cues; autonomous library clocks freeze. Empty initial records survive normalization. Larkspur retains the actual kanban-move and comparison-table components. |
| 7 | Presenter Tier 2 | [layers.tsx](../../src/film/layers.tsx), [conform-plan.ts](../../scripts/conform-plan.ts). Bounds checked against active reels/tiktok profile; canonical presenter assets unchanged. Actual sampled bounds are in both conformance reports. No silent overlap override was added. |
| 8 | Clipping/crowding repair | Real vision flags drove fewer competing objects, larger context labels, focus-only detail, protected text backgrounds and more vertical space. Larkspur uses a full StageSlot; portrait Kanban cards wrap complete titles and metadata in taller cards. [Mara repair](mara-final/repair.json), [Larkspur repair](larkspur-final/repair.json). |
| 9 | Transition/continuity | One DirectedStage remains mounted; stable keyed objects move between renderer-owned detail/system/comparison/recap constructions. Reset is explicit; other boundaries interpolate. The persistent spine stays fixed. |
| 10 | Persistent objects | Object IDs index a phrase-gated cross-film ledger; original order #1042 and the new replacement order are distinct. [Direction audit](mara-v1-production/continuity-audit.json). |
| 11 | Presenter blocking | Cue-aligned lead/beside/away shots pass through layoutFor and PresenterLayer. Phone comparisons and conformance bounds cover actual rendered blocking. |
| 12 | Recap continuity | recapRefs retrieve earlier object IDs. Recap events display RECAP state labels while retaining actual history. Conditional branches are explicitly HYPOTHETICAL/IF, with ACTUAL history labeled separately. |
| 13 | New Mara render | [film.mp4](mara-v1-production/film.mp4). Cold regression: [film.mp4](larkspur-verified/film.mp4). |
| 14 | Phone evidence | [Mara manifest](mara-v1-production/evidence/manifest.json), [first 330px comparison sheet](mara-v1-production/evidence/comparison-01.png), [Tools before](mara-v1-production/evidence/tools-action-before.mp4) / [after](mara-v1-production/evidence/tools-action-after.mp4), [recap before](mara-v1-production/evidence/recap-before.mp4) / [after](mara-v1-production/evidence/recap-after.mp4); additional boundary/branch excerpts and numbered sheets. [Larkspur manifest](larkspur-verified/evidence/manifest.json), [apply before](larkspur-verified/evidence/apply-before.mp4) / [after](larkspur-verified/evidence/apply-after.mp4), all 151 phone frames and [seven full-frame sheets](larkspur-verified/evidence/frame-by-frame-01.png) for 75–80 seconds. |
| 15 | Tier 1 | Both delivery MP4s pass all technical/container checks: [Mara](mara-v1-production/technical-qc.json), [Larkspur](larkspur-verified/technical-qc.json). |
| 16 | Tier 2 | Both pass: [Mara](mara-v1-production/conformance.json), [Larkspur](larkspur-verified/conformance.json). Candidate audits verify script/audio/alignment preservation and every declared cue. |
| 17 | Tier 3 | Complete real API critiques: [Mara gaps](mara-v1-production/critic-gaps/critic.json), [Mara targeted frames](mara-v1-production/critic-targeted/critic.json), [Larkspur gaps](larkspur-verified/critic-gaps/critic.json), [Larkspur cue frames](larkspur-verified/critic-targeted/critic.json). Gap results: {counts}. Raw API responses retained. |
| 18 | G01–G13 | Complete real before/after [comparison](mara-v1-production/comparison-critic/comparison.json), summarized below. Required creative criteria: {corestatus}. |
| 19 | Remaining defects | [Frame-based adjudication and remaining limits](mara-v1-production/REVIEW_ADJUDICATION.md) distinguishes actual observations from unsupported timing/presence claims. Raw flags and comparison findings remain disclosed below and in the linked critiques. Vision suggestions that would redesign captions/spine or confuse retained actual history with a hypothetical are not applied blindly. |
| 20 | Renderer limits | Library semantic states are cue-driven snapshots at a frozen native frame; a generic animated transition between every arbitrary library prop snapshot is not implemented. Existing clocks/native startup delays must be neutralized in props. Fixed renderer-owned constructions still limit authorship and contextual text density. No renderer/framework migration. |
| 21 | Recommendation | **{recommendation}**. The evidence establishes real execution, not automatic creative approval. No later phase started, and studio memory was not promoted. |

The execution loop retained initial failures: real Mara baseline critique flagged 12/25 gap frames; first directed Mara candidate flagged 22/25. Initial cue-gated Larkspur flagged 16/24; its full-stage repair flagged 6/24 before the portrait title/metadata wrapping fix. These failures caused actual repair and rerendering. Caption fragments are intentional aligned chunks, so only physical glyph clipping is considered clipping. Empty retained history/conditional differences are reviewed according to the handoff, not treated as arbitrary state reversals.

Final loop repairs also restore the Tools agent/API/order chain, protect labels while objects change positions, reserve the closing presenter's space, and use the existing lead gesture on sparse introduction/summary shots. The reply remains writing until the exact answered cue; its actual sent event was recovered from the real model's supported but misplaced additions array and validated. [Final real repair](mara-v1-production/repair.json), [preceding real repair](mara-final-production/repair.json), [cold row repair](larkspur-unclear-repair/repair.json). Larkspur's initial 70.000-second criticism was 79 milliseconds before its unclear cue; the actual 70.300-second frame confirmed correct state and exposed the cramped row subsequently repaired. The earlier G10 critic incorrectly reported a presenter at 96 seconds; the extracted frame has none. Raw critiques remain unchanged, and the final comparisons use broader entry/action/result sequences.

The Larkspur frame-by-frame check combines authoritative props with decoded production pixels. All 151 frames from 75.000–80.000s leave assignments in Requests. First assignment cue: 81.898s. Maximum decoded stage change above the compression threshold before the cue: {framecheck['maximumChangedFraction']:.6%}; visible change just after the cue: {framecheck['afterCueChange']['changedFractionAbove12']:.6%}. [Full rendered check](larkspur-verified/evidence/frame-by-frame-render-check.json).

| G-rule | Relative comparison | Critic acceptance | Remaining observations / review limits |
| --- | --- | --- | --- |
{grows}

Files inherited from the completed local implementation: src/film/direction.ts, server/direct-structure.ts, src/film/DirectedStage.tsx, src/film/state-cues.ts, src/film/normalize.ts, src/film/types.ts, src/film/StructuredFilm.tsx, src/film/layers.tsx, scripts/conform-plan.ts, server/dev.ts, studio/App.tsx, scripts/produce.ts, scripts/inspect-render.ts, scripts/direct-continuity.ts, scripts/render-continuity.ts, scripts/continuity-regression.ts, scripts/remotion-cli.cjs, scripts/windows-run.cjs.

Resumption changes: direction.ts (exact contiguous aligned-word cue matching, including short words), DirectedStage.tsx (case status, branch isolation, context reflow, recap state execution, explicit branch/actual scope, reserved presenter space, moving-label protection), normalize.ts (preserve cue data/empty initial records), identity.ts (honor explicit settling speed), kanban-move/index.tsx (portrait wrapping/taller cards), procedural.tsx (caption-only record bottom padding), direct-continuity.ts (bounded input, larger real output allowance, completion metadata), inspect-render.ts (strict nonempty JSON evidence, additional targets, partial-progress durability, concurrent independent inspections, explicit real provider), render-continuity.ts (bounded compositor cache and explicit production JPEG intermediate settings), and new server/vision.ts, verify-continuity-services.ts, direct-component-state.ts, repair-continuity-plan.ts, audit-continuity-candidate.ts, compare-continuity.ts, continuity-evidence.py, continuity-frame-check.py, write-continuity-evidence.py.

Per-film review provenance: [initial-detail correction](mara-delivery/review-repair.json) removes facts not yet narrated when the email is introduced; [action-shot reconciliation](mara-delivery/action-shot-repair.json) reuses two valid shots from the real model's first repair response while discarding its invalid event-index edits. Neither is a replacement FilmDirection authored as an offline substitute.

Inspection limits: vision judged actual extracted phone frames and ordered entry/action/result sequences; no continuous audiovisual viewing claim is made. Deterministic alignment and bounds conclusions come from Tier 2/audits. The before/after moving excerpts are provided for Source of Truth review. No exact timing, easing or universal artistic rule was promoted from a still-frame opinion.

Production requests: [initial services](service-verification.json), [OpenAI direction](openai-direction-verification.json), [OpenAI image input](openai-vision-verification.json). The explicit real-provider adapter follows [official OpenAI image-input documentation](https://developers.openai.com/api/docs/guides/images-vision?api-mode=chat). Environment records: [Mara](mara-v1-production/render-environment.json), [Larkspur](larkspur-verified/render-environment.json). SHA-256 manifests bind the QC/evidence to the delivery MP4s. Temporary disk exhaustion was recovered by clearing only named disposable render directories created during this session, then rendering sequentially with a bounded decoding cache.
'''
(root/'ACCEPTANCE_EVIDENCE.md').write_text(text,encoding='utf-8')
status=f'''Continuity & Film Direction v1 — real execution complete.

Recommendation: {recommendation}. No later phase started. Return to Source of Truth for reconciliation.

The complete 21-item evidence is in [ACCEPTANCE_EVIDENCE.md](ACCEPTANCE_EVIDENCE.md). Final renders are [Mara](mara-v1-production/film.mp4) and [Larkspur](larkspur-verified/film.mp4). Both use production fonts and retained Eric A audio/script/alignment. Baselines were preserved. No quarantined substitute is acceptance evidence.

Outbound HTTPS, authenticated real direction/vision and all production-font requests worked. Anthropic later exhausted its credits during an inspection; its failed partial report remains under mara-delivery-final/critic-targeted. The already configured OpenAI gpt-4.1 provider passed authenticated text and image requests and completed the final Mara vision reviews. This provider change and its interpretation limits are disclosed in the evidence.

Tier 1 and Tier 2 pass for both deliveries. Tier 3 is complete: {counts}. All 13 final real before/after comparisons report improvement; all eight required creative criteria are covered. Factual mistakes in raw vision output are adjudicated with saved frames and recorded cues in [REVIEW_ADJUDICATION.md](mara-v1-production/REVIEW_ADJUDICATION.md). Some contextual labels stay small; abstract action vocabulary and cue-driven library snapshots remain renderer limits.

All 151 decoded Larkspur frames from 75–80 seconds hold Requests. First assignment cue: 81.898 seconds. Final Mara regression confirms writing before the answered cue, sent after it, and answered actual history during hypothetical/recap.

TypeScript and Python checks pass. Final SHA-256 provenance is in acceptance-summary.json. The original restricted-session report is preserved as EXECUTION_STATUS.restricted-session.md. Loop history remains in its original candidate directories; final evidence uses only the two final MP4s named above.
'''
(root/'EXECUTION_STATUS.md').write_text(status,encoding='utf-8')
(mara/'NOTES.md').write_text('Final real production v1 delivery. Technical QC and conformance pass; retained script, Eric A audio and alignment are unchanged. Complete gap/targeted/G reviews and factual qualifications are linked in REVIEW_ADJUDICATION.md. Direction is real API output with recorded real-model/per-film repairs. The final code repair protects all labels during a spatial reframe, including labels on newly visible objects. Baseline and prior candidates remain preserved. No studio-memory promotion or later phase.\n',encoding='utf-8')
summary={'generatedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'recommendation':recommendation,'realServicesVerified':True,'maraVideo':str(mara/'film.mp4'),'larkspurVideo':str(cold/'film.mp4'),'tier1':True,'tier2':True,'tier3Complete':True,'gComparisonComplete':True,'gComparisons':[{k:f.get(k) for k in ['ruleCode','comparison','acceptanceMet']} for f in comparison['findings']],'noQuarantinedEvidence':True,'laterPhaseStarted':False}
artifact_files=[root/'ACCEPTANCE_EVIDENCE.md',root/'EXECUTION_STATUS.md',root/'service-verification.json',root/'openai-direction-verification.json',root/'openai-vision-verification.json']
for folder in [mara,cold]:
    artifact_files += [folder/f for f in ['film.mp4','props.json','input-script.txt','technical-qc.json','conformance.json','continuity-audit.json','render-environment.json','critic-gaps/critic.json','critic-targeted/critic.json','evidence/manifest.json']]
    artifact_files += [p for p in [folder/'critic-gaps/critic-input.json',folder/'critic-targeted/critic-input.json',folder/'NOTES.md'] if p.exists()]
artifact_files += [mara/'film-direction.json',mara/'comparison-critic/comparison.json',mara/'REVIEW_ADJUDICATION.md',cold/'evidence/frame-by-frame-render-check.json']
summary['artifactSha256']={str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in artifact_files}
(root/'acceptance-summary.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')
print(root/'ACCEPTANCE_EVIDENCE.md')
